TRAIN_DATA = [
    ("Substitution -  Crystal Palace. Yohan Cabaye for Bakary Sako  - injury.", {"entities": [(16, 30, "ORG"), (32, 44, "PERSON"),(49, 60, "PERSON")]}),
    ("Shane Duffy  - Brighton and Hove Albion -  receive yellow card for hand ball.", {"entities": [(0, 11, "PERSON"),(15, 23, "ORG"), (28, 39, "PERSON")]}),
    ("Second Half ended - Bournemouth 4, Huddersfield Town 0.", {"entities": [(20, 31, "ORG"),(35, 52, "ORG")]}),
    ("New attacking attempt. Oliver McBurnie  - Swansea City -  shot with the head from the centre of the box is saved in the top left corner. Assist -  Luciano Narsingh with a cross.", {"entities": [(23, 38, "PERSON"),(42, 54, "ORG"), (147, 163, "PERSON")]}),
    ("Offside - West Bromwich Albion. Matt Phillips with a pass, however Salomón Rondón is in offside.", {"entities": [(10, 30, "ORG"),(32, 45, "PERSON"), (67, 81, "PERSON")]}),
    ("Substitution -  Huddersfield Town. Martin Cranie for Elias Kachunga.", {"entities": [(16, 33, "ORG"),(35, 48, "PERSON"), (53, 67, "PERSON")]}),
    ("Corner -  Southampton. Conceded by Matthew Lowton.", {"entities": [(10, 21, "ORG"),(35, 49, "PERSON")]}),
    ("Goal!  Watford 0, Manchester City 3. Gabriel Jesus (Manchester City) right footed shot from the centre of the box to the bottom left corner. Assisted by Sergio Agüero with a through ball.", {"entities": [(7, 14, "ORG"),(18, 33, "ORG"), (37, 50, "PERSON"), (52, 67, "ORG"), (153, 166, "PERSON")]}),
    ("Substitution -  Tottenham Hotspur. Fernando Llorente for Jan Vertonghen  - injury.", {"entities": [(16, 33, "ORG"),(35, 52, "PERSON"), (57, 71, "PERSON")]}),
    ("New attacking attempt. Eric Maxim Choupo-Moting  - Stoke City -  shot with the head from the left side of the box is saved by goalkeeper in the centre of the goal. Assist -  Erik Pieters with a cross.", {"entities": [(23, 47, "PERSON"),(51, 61, "ORG"), (174, 186, "PERSON")]}),
    ("Attempt blocked. Jason Puncheon (Crystal Palace) left footed shot from outside the box is blocked.", {"entities": [(17, 31, "PERSON"),(33, 47, "ORG")]}),
    ("Goal!  Everton 1, Southampton 1. Tom Davies  - Everton -  shot with right foot from outside the box to the centre of the goal. Assist -  Idrissa Gueye.", {"entities": [(7, 14, "ORG"),(18, 29, "ORG"), (33, 43, "PERSON"),(47, 54, "ORG"), (137, 150, "PERSON")]}),
    ("Theo Walcott  - Everton -  won a free kick on the left wing.", {"entities": [(0, 12, "PERSON"),(16, 23, "ORG")]}),
    ("Fouled by Morgan Schneiderlin  - Everton", {"entities": [(10, 29, "PERSON"),(33, 40, "ORG")]}),
    ("Offside - Manchester United. Chris Smalling with a pass, however Juan Mata is in offside.", {"entities": [(10, 27, "ORG"),(29, 43, "PERSON"), (65, 74, "PERSON")]}),
    ("Substitution -  Huddersfield Town. Laurent Depoitre for Tommy Smith.", {"entities": [(16, 33, "ORG"),(35, 51, "PERSON"), (56, 67, "PERSON")]}),
    ("Substitution -  West Bromwich Albion. Jay Rodriguez for Matt Phillips.", {"entities": [(16, 36, "ORG"),(38, 51, "PERSON"), (56, 69, "PERSON")]}),
    ("Henrikh Mkhitaryan  - Manchester United -  won a free kick on the left wing.", {"entities": [(0, 18, "PERSON"),(22, 39, "ORG")]}),
    ("New attacking attempt. Marouane Fellaini  - Manchester United -  shot with right foot from the centre of the box is saved in the left corner. Assist -  Eric Bailly.", {"entities": [(23, 40, "PERSON"),(44, 61, "ORG"), (152, 163, "PERSON")]}),
    ("Substitution -  Chelsea. Pedro for Eden Hazard.", {"entities": [(16, 23, "ORG"),(25, 30, "PERSON"), (35, 47, "PERSON")]}),
    ("Attempt blocked. Sergio Agüero (Manchester City) left footed shot from the centre of the box is blocked.", {"entities": [(17, 30, "PERSON"),(32, 47, "ORG")]}),
    ("Joshua King (Bournemouth) wins a free kick on the right wing.", {"entities": [(0, 11, "PERSON"),(13, 24, "ORG")]}),
    ("Jay Rodriguez (West Bromwich Albion) wins a free kick in the attacking half.", {"entities": [(0, 13, "PERSON"),(15, 35, "ORG")]}),
    ("Hand ball by Jacob Murphy (Newcastle United).", {"entities": [(13, 25, "PERSON"),(27, 43, "ORG")]}),
    ("Fouled by Kelechi Iheanacho  - Leicester City", {"entities": [(10, 27, "PERSON"),(31, 45, "ORG")]}),
    ("Corner -  Brighton and Hove Albion. Conceded by Declan Rice.", {"entities": [(10, 34, "ORG"),(48, 59, "PERSON")]}),
    ("Willian  - Chelsea -  won a free kick in attack.", {"entities": [(0, 7, "PERSON"),(11, 18, "ORG")]}),
    ("Fouled by Granit Xhaka  - Arsenal", {"entities": [(10, 22, "PERSON"),(26, 33, "ORG")]}),
    ("Substitution -  Arsenal. Olivier Giroud for Alexandre Lacazette.", {"entities": [(16, 23, "ORG"),(25, 39, "PERSON"), (44, 63, "PERSON")]}),
    ("Delay in match Phil Bardsley  - Burnley -   - injury.", {"entities": [(15, 28, "PERSON"),(32, 39, "ORG")]}),
    ("Pedro Obiang  - West Ham United -  won a free kick in defence.", {"entities": [(0, 12, "PERSON"),(16, 31, "ORG")]}),
]